fix this template so it doesn't barf
```
  pulumi:pulumi:Stack (pulumi-noom-yaml-pulumi-noom-yaml):
    Traceback (most recent call last):
      File "/Users/allixsenos/.pulumi/plugins/resource-noom-v0.0.1/run-provider.py", line 19, in <module>
        import noom_provider
      File "/Users/allixsenos/.pulumi/plugins/resource-noom-v0.0.1/noom_provider/__init__.py", line 6, in <module>
        with open(os.path.join(os.path.dir(__file__), 'schema.json')) as schema_file:
    AttributeError: module 'posixpath' has no attribute 'dir'
```